### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by Youni2017** [C2H5OH-Consumer/temp4hifu#2]
# Feedback:  
The repository demonstrates a strong effort, with clear documentation, well-structured code, and thoughtful implementation. Your work stands out for its attention to detail. Thank you for submitting your project early; bonus points have been awarded accordingly:)

# Problem:  
While the project includes a `setup.py` file and is available on PyPI, the following error occurs when attempting to run the application after installation with `pip`:  

```python
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 158, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/temp4hifu/startApp.py", line 172
    match DROP_field2D:
          ^
SyntaxError: invalid syntax

**Comment by C2H5OH-Consumer** [comment]
Thank you for the feedback!

This is interesting error I didn't encounter previously; I had tested this with a friend on his machine. The app worked fine, with no syntax error returned when interacting with that specific dropdown menu. 

Would you mind providing more information about the error please?

1. Did the application in the terminal return the link to the browser? Or was this error thrown after the application was available to be used? 
2. What version are you using? 
3. Did you attempt to input a random word into the dropdown menu? If there is a space or an accidental adjustment to the name of the input string, the app was not set up to handle incorrect inputs which is an oversight on my side.

**Comment by Youni2017** [comment]
Apologies for not being able to provide an immediate answer to the question you mentioned above. A better approach would be to consult Prof. Hellerstein, who is the primary grader for this project and the one who left the comment. Thank you for your dedication and high standards in coding work:)
